# Generated by Django 2.2.6 on 2019-10-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_data', models.DateField()),
                ('body', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
