# Generated by Django 2.2.6 on 2019-10-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_data',
            field=models.DateTimeField(),
        ),
    ]
